import express from "express";
import cors from "cors";
import cookies from "cookie-parser";
import morgan from "morgan";
import habitRoutes from "./routes/habits.routes.js";
import authRoutes from "./routes/auth.routes.js";
import notesRoutes from "./routes/notes.routes.js";
import goalsRoutes from "./routes/goals.routes.js";
import statsRoutes from "./routes/stats.routes.js";
const app = express();
app.use(cookies());
app.use(morgan("dev"));
app.use(cors());
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/habits", habitRoutes);
app.use("/api/notes", notesRoutes);
app.use("/api/goals", goalsRoutes);
app.use("/api/stats", statsRoutes);
export default app;
